### ISSUE TITLE
How are transposable elements determined?

### ISSUE THREAD

**Issue by snayfach** [bobeobibo/phigaro#18]
I couldn't find this information in the publication.

Thanks,
Stephen

**Comment by bobeobibo** [comment]
We mark possible transposable element insertions if we detect more than two consecutive transposases or integrases inside the prophage. Integrases and transposases are determined according to custom pVOG HMM lists.

We added this feature because TE can massively integrate into prophages (or anywhere, actually...) and possibly interrupt their genomic structure. We think this is what the microbiologists should be aware of when exploring prophages.
