### ISSUE TITLE
Can't understand the option "-d: Exclude sequences with length < 20000 automatically". 

### ISSUE THREAD

**Issue by ChenTianYi99** [bobeobibo/phigaro#31]
Hello, currently, i want to identity the viral sequences with length > 1000, but phigaro seems to automatically exclude sequences  with length < 20000. If i don't add the option "-d", it will prompt me whether to remove these sequences. So  how to deal with the problem…… Looking forward to your reply.

**Comment by PollyTikhonova** [comment]
Hello! Yeah, this happens due to limits of Prodigal which is used to annotate sequences. Thus, right now, Phigaro does not support sequences less than 20kbp. We'll think about that option in future. 
BUT I'd like to make it clear. Basically, we can't really name the boundaries of viral parts in such a short sequences because practically, the whole sequence will be either viral or not (with little exclusions).
BUT here is the algorithm what you can do now to identify if your sequence is viral or not based on Phigaro.
1. Run Prodigal with -p meta mode:
`prodigal -i sequences.fasta -a prodigal_meta.faa -o prodigal_output.out -p meta`
It will produce about 20 or less genes.
2. Run Phigaro in delete sequences mode, provide the prodigal .faa file and ask not to delete the temporary files:
`phigaro -f sequences.fasta --no-cleanup -o output -S prodigal:prodigal_meta.faa -d`
In `proc/hmmer`  you'll find the list of genes which were assigned with viral ids - pVOGs (looks like VOG0000).
But BE CAREFUL! The sequences and genes are presented in random order!
4. For each sequence you should make a list of VOGs: some genes could be assigned to several VOGs - choose the one with the least e-value.
5. According to our research there are most likely viral VOGs and less likely. You'll find the list of most likely viral VOGs  here:
[https://github.com/bobeobibo/phigaro/blob/master/phigaro/const.py](https://github.com/bobeobibo/phigaro/blob/master/phigaro/const.py): at the variable `DEFAULT_WHITE_LIST `.
You can assign your sequence as viral if it contains at least one VOG from the `DEFAULT_WHITE_LIST` .
6.  In addition, you can look at other metrics: fraction of VOG assigned genes among all genes, fraction of white list VOGs among all VOG assigned genes or all genes. 

Hope, this will help you!

**Comment by ChenTianYi99** [comment]
So glad to receive your reply! I will try to test my data according to your suggestions. Thank you for your help!Great day! On 04/02/2021 17:47, Polina wrote: 
Hello! Yeah, this happens due to limits of Prodigal which is used to annotate sequences. Thus, right now, Phigaro does not support sequences less than 20kbp. We'll think about that option in future.
BUT I'd like to make it clear. Basically, we can't really name the boundaries of viral parts in such a short sequences because practically, the whole sequence will be either viral or not (with little exclusions).
BUT here is the algorithm what you can do to identify if your sequence is viral or not based on Phigaro.

Run Prodigal with -p meta mode:
prodigal -i sequences.fasta -a prodigal_meta.faa -o prodigal_output.out -p meta
It will produce about 20 or less genes.
Run Phigaro in delete sequences mode, provide the prodigal .faa file and ask not to delete the temporary files:
phigaro -f sequences.fasta --no-cleanup -o output -S prodigal:prodigal_meta.faa -d
In proc/hmmer  you'll find the list of genes which were assigned with viral ids - pVOGs (looks like VOG0000).
But BE CAREFUL! The sequences and genes are presented in random order!
For each sequence you should make a list of VOGs: some genes could be assigned to several VOGs - choose the one with the least e-value.
According to our research there are most likely viral VOGs and less likely. You'll find the list of most likely viral VOGs  here:
https://github.com/bobeobibo/phigaro/blob/master/phigaro/const.py: at the variable DEFAULT_WHITE_LIST .
You can assign your sequence as viral if it contains at least one VOG from the DEFAULT_WHITE_LIST .
In addition, you can look at other metrics: fraction of VOG assigned genes among all genes, fraction of white list VOGs among all VOG assigned genes or all genes.

Hope, this will help you!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/bobeobibo/phigaro/issues/31#issuecomment-812458088",
"url": "https://github.com/bobeobibo/phigaro/issues/31#issuecomment-812458088",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
