### ISSUE TITLE
Calculation of the number of intact and defective prophages

### ISSUE THREAD

**Issue by abhinavyesss** [bobeobibo/phigaro#32]
Hello

As a result, phigaro gives out various fields such as taxonomy, transposable, VOG, et cetera for each prophage found. Is there any way to get the intact or defective status using that information?

**Comment by bobeobibo** [comment]
Not really. Phigaro uses pVOG HMMs that are sensitive to distant homologues of known phage genes (which makes it great for predicting completely new prophage sequences). For some reasons, these HMMs are designed in such a way that we can't always tell if we see structural proteins or assembly proteins (e.g., tail fiber proteins and tail assembly proteins might be in the same pVOG). And in order to tell if a prophage is intact or defective we need to make sure that it has all the genes needed for successful replication, assembly and lysis.

You can get a rough idea about that looking at html visualizations that Phigaro provides. If you prophage seems to have enough structural/replication/assembly genes, I recommend using Phigaro's coordinates +/- 3Kbp and blasting each of the proteins inside this area in order to get better gene annotations.
