### ISSUE TITLE
Short Sequences 

### ISSUE THREAD

**Issue by antixz1** [bobeobibo/phigaro#36]
Is there a reason Phigaro dismisses contigs <20000 bp? Is there any way to alter the threshold?

**Comment by PollyTikhonova** [comment]
Hi, I am so sorry I was sure I addressed the question, but it seems it happened only in my head
Yes, there is a technical limitation - Prodigal, which is used for sequence annotation do not process sequences shorter this length.
But speaking about the opportunity of allowing Phigaro to run such short sequences, my colleague and I concluded that Phigaro, probably would make no sense at this mode, because the sequence is too short to identify several viral items.
Anyway, I am citing here my previous comment to the same question with the algorithm, which would allow you manually to extract the virality of your sequence using Phigaro: https://github.com/bobeobibo/phigaro/issues/31
Hope, it's helpful!
